baseURL = "/"
languageCode = "en-us"
title = "The Hennessy Group"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We make your loyalty and incentive programs with persuasive design and persuasive technology."
    meta_og_title = "The Hennessy Group"
    meta_og_type = "website"
    meta_og_url = "https://hennessygrp.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "The Hennessy Group LLC provides loyalty and incentive advisory to companies who believe in people."
    meta_twitter_card = "summary"
    meta_twitter_site = "@hennessygroup"
    meta_twitter_creator = "@hennessygroup"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

# [[menu.main]]
#     name = "Work"
#     url = "/work/"
#     weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"